name = "420th Customizations"
author = "thegamecracks"
prefix = "fdelta"
mainprefix = "z"

[version]
major = 2026
minor = 1
patch = 23

[files]
include = [
    "logo.jpg",
    "README.md",
]

[hemtt.build]
pdrive = "disallow"

[hemtt.check]
pdrive = "ignore"

[signing]
private_key_hash = "492e44ab7e8c33da235232d06e4e191565937c81"
